

//-------------------------- EJERCICIO 1---------------------------//

/*
Comprar los mas caros:
Roberto: $1.5 USD
Pedro: $1.7 USD
Juan: $3 USD

Precios de helados:
Palito de helado de agua: $0.6 USD
Palito de helado de crema: $1 USD
Bombón helado marca Heladix: $1.6 USD
Bombón helado marca Heladovich: $1.7 USD
Bombón helado marca Helardo: $1.8 USD
Potecito de helado con confites: $2.9 USD
Pote de 1/4 Kg: $2.9 USD
*/

/*
?SOLUCIONES

* Pedir que ingresen el monto que tienen y mostrarles el helado más caro que puedan comprar.

* Si hay 2 o mas con el mismo precio, mostrar ambos.

* Juan quiere saber cuanto es el vuelto.
*/

// Solución creada con bloques if/else if/else, con ayudas de depuración en consola
alert("Buenas!!");

let nombre = prompt("Ingrese su nombre por favor");
alert("Hola " + nombre);

dinero = prompt("Favor indique el monto máximo, tenemos helados desde $0.6 hasta $2.9");
dinero = parseFloat(dinero);
console.log(typeof(dinero));
/*
This code is checking if the user\'s input is a number If it isn\'t then an alert 
will pop up saying that the value entered was not a number Then it checks to see 
if the amount of money they put in is greater than or equal to 0 and less than 1 
dollar If so then an alert pops up telling them what product they should buy and 
how much change they need back If their money was greater than or equal to 2 dollars 
but less than 3 dollars then another alert pops up telling them what product they 
should buy and how much change they need back If their money was greater than or 
equal to 3 dollars but less than 4 dollars then another alert pops up telling them 
what product they should buy and how much change they need back If their money was 
exactly 4 dollars or more then another alert pops up telling them what product they 
should buy and how much change they need back
- generated by stenography autopilot [ 🚗👩‍✈️ ]
*/

if (dinero >= 0.6 && dinero < 1){  
  alert(nombre +" te recomiendo el helado de Agua $0.6");
  vuelto = (dinero - 0.6);
  console.log(typeof(vuelto));
  console.log(vuelto);
  total = dinero - 0.6;
  console.log(total);
  alert("tu vuelto es: " + (vuelto.toFixed(2)));

  
} else if (dinero >= 2.9){

  alert(nombre +" te recomiendo el pote de helado con confites o el pote de 1/4 Kg $2.9");
  vuelto = (dinero - 2.9);
  console.log(typeof(vuelto));
  console.log(vuelto);
  total = dinero - 1.7;
  console.log(total);
  alert("tu vuelto es: " + vuelto.toFixed(2));


} else if (dinero >= 1.8 && dinero < 2.9){

  alert(nombre + " te recomiendo el helado de marca Helardo  $1.8");
  vuelto = (dinero - 1.8);
  console.log(typeof(vuelto));
  console.log(vuelto);
  total = dinero - 1.8;
  console.log(total);
  alert("tu vuelto es: " + (vuelto.toFixed(2)));


} else if (dinero == 1.7){

  alert(nombre +" te recomiendo el helado de marca Heladovich $1.7");
  
  alert("Sin vuelto");
  
} else if (dinero == 1.6){
  alert(nombre +" te recomiendo el helado de marca Heladix $1.6");
  
  alert("Sin vuelto");
  
} else if (dinero >= 1 && dinero < 1.6){

  alert(nombre +" te recomiendo el helado de Crema $1");
  vuelto = (dinero - 1);
  console.log(typeof(vuelto));
  console.log(vuelto);
  total = dinero - 1.0;
  console.log(total);
  alert("tu vuelto es: " + (total.toFixed(2)));

} else{
  alert("Lo sentimos " + nombre + " no te alcanza para ninguno");

}

alert("Gracias " + nombre + " que tengas un buen día");